name: mmzhong
timezone: Asia/Shanghai
permalink: /blog/:year/:month/:day/:title
title: Zhong Ming
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge
exclude: 
  - node_modules